// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GibbsGMM
SEXP GibbsGMM(SEXP yS, SEXP itS, SEXP biS, SEXP prS);
RcppExport SEXP _multiPotts_GibbsGMM(SEXP ySSEXP, SEXP itSSEXP, SEXP biSSEXP, SEXP prSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type itS(itSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type biS(biSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prS(prSSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsGMM(yS, itS, biS, prS));
    return rcpp_result_gen;
END_RCPP
}
// GibbsPotts
SEXP GibbsPotts(SEXP yS, SEXP betaS, SEXP muS, SEXP sigmaS, SEXP nS, SEXP bS, SEXP prS, SEXP itS, SEXP biS);
RcppExport SEXP _multiPotts_GibbsPotts(SEXP ySSEXP, SEXP betaSSEXP, SEXP muSSEXP, SEXP sigmaSSEXP, SEXP nSSEXP, SEXP bSSEXP, SEXP prSSEXP, SEXP itSSEXP, SEXP biSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betaS(betaSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type muS(muSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmaS(sigmaSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bS(bSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prS(prSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type itS(itSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type biS(biSSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsPotts(yS, betaS, muS, sigmaS, nS, bS, prS, itS, biS));
    return rcpp_result_gen;
END_RCPP
}
// MCMCPotts
SEXP MCMCPotts(SEXP yS, SEXP nS, SEXP bS, SEXP itS, SEXP biS, SEXP prS, SEXP mhS);
RcppExport SEXP _multiPotts_MCMCPotts(SEXP ySSEXP, SEXP nSSEXP, SEXP bSSEXP, SEXP itSSEXP, SEXP biSSEXP, SEXP prSSEXP, SEXP mhSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bS(bSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type itS(itSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type biS(biSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prS(prSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mhS(mhSSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMCPotts(yS, nS, bS, itS, biS, prS, mhS));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiPotts_GibbsGMM", (DL_FUNC) &_multiPotts_GibbsGMM, 4},
    {"_multiPotts_GibbsPotts", (DL_FUNC) &_multiPotts_GibbsPotts, 9},
    {"_multiPotts_MCMCPotts", (DL_FUNC) &_multiPotts_MCMCPotts, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiPotts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
