# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsPotts1d <- function(yS, zS, betaS, muS, sdS, nS, bS, prS, itS) {
    .Call(`_multiPotts_gibbsPotts1d`, yS, zS, betaS, muS, sdS, nS, bS, prS, itS)
}

mdgibbsPotts <- function(yS, betaS, muS, sigmaS, nS, bS, prS, itS) {
    .Call(`_multiPotts_mdgibbsPotts`, yS, betaS, muS, sigmaS, nS, bS, prS, itS)
}

rcpparma_hello_world <- function() {
    .Call(`_multiPotts_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_multiPotts_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_multiPotts_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_multiPotts_rcpparma_bothproducts`, x)
}

