# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GibbsGMM <- function(yS, itS, biS, prS) {
    .Call(`_multiPotts_GibbsGMM`, yS, itS, biS, prS)
}

GibbsPotts <- function(yS, betaS, muS, sigmaS, nS, bS, prS, itS, biS) {
    .Call(`_multiPotts_GibbsPotts`, yS, betaS, muS, sigmaS, nS, bS, prS, itS, biS)
}

MCMCPotts <- function(yS, nS, bS, itS, biS, prS, mhS) {
    .Call(`_multiPotts_MCMCPotts`, yS, nS, bS, itS, biS, prS, mhS)
}

