# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' monodimensional gaussian mixture model gibbs sampler
#' @description Yields the posterior of a 1D-GMM by building a Gibbs MCM algorithm
#' @param yS a vector of data
#' @param itS total number of iterations
#' @param biS burn in iterations
#' @param prS is a list of priors for the model, it includes:
#' @param    mu: the prior mean of the normal distr of the mean of each cluster (vector)
#' @param    mu.sd: the prior sd of the normal distr of the mean of each cluster (vector)
#' @param    sigma: the shape parameter of the gamma for the sd prior (vector)
#' @param    sigma.nu: the rate parameters of the gamma for the sd prior (vector)
#' @param    lambda: the parameters of the dirichlet for the weights of the mixture (vector)
#' @paramsalitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#' @return List of the posterior of the Random Variables
NULL

#' multidimensional GMM gibbs sampler
#' @description Yields the posterior of a 1D-GMM by building a Gibbs MCM algorithm
#' @param yS a matrix of data, samples on the cols, features on the rows
#' @param itS total number of iterations
#' @param biS burn in iterations
#' @param prS is a list of priors for the model, it includes:
#' @param   mu: the prior mean of the normal distr of the mean of each cluster (matrix)
#' @param    mu.sigma: the covariance matrices of the normal distr of the mean of each cluster (3D array)
#' @param    sigma.V0: the V= matrix for the wishart prior of the covariance matrices (3D array)
#' @param    sigma.n0: the n0 parameters of the wishart prior for the covariance matrices (vector)
#' @param    lambda: the parameters of the dirichlet for the weights of the mixture (vector)
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#' 
#' @return List of the posterior distribution of the random variables
NULL

#' monodimensional Potts model gibbs sampler with beta sampled via Pseudolikelihood
#' @description Build a Gibbs MCMC to yield the posterior of the random variables of a Potts model with 
#' random beta. 
#' 
#' @details This algorithm contains a metropolis-hastings step for the full conditional
NULL

#' wrapper function for the gibbs sampler for the GMM
#' 
#' @description this identifies whether we are in the 1D or mD case and calls the appropriate function
#' @details the prior list prS must include: mu: the prior mean of the normal distr of the mean of each cluster (vector)   mu.sd: the prior sd of the normal distr of the mean of each cluster (vectorsigma the shape parameter of the gamma for the sd prior (vector)sigma.nu the rate parameters of the gamma for the sd prior (vector)
#' itS total number of iterations
#' @param ys the data vector (1D) or matrix (mD)
#' @param prS is a list of priors for the model
#' @param itS max number of iterations
#' @param biS number of burn-in iterations
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#'
#'@return List with the posterior samples of each random variable
GibbsGMM <- function(yS, prS, itS, biS, salitS) {
    .Call(`_multiPotts_GibbsGMM`, yS, prS, itS, biS, salitS)
}

#' wrapper function for the gibbs sampler for the potts model with fixed beta
#' @description this identifies whether we are in the 1d or md case and calls the appropriate function
#' 
#' @param yS a matrix (vector) of data, samples on the cols, features on the rows
#' @param betaS is the value of beta to use for the gibbs Distribution
#' @param muS is a matrix containing the starting point of the mu of the chain, one col for cluster
#' @param sigmaS is a 3D array containing the starting values of the covariance matrices of the potts model, one per cluster
#' @param nS is the neighbours object from BayesImageS
#' @param bs is the blocks object from BayesImageS
#' @param prS is a list of priors for the model, it includes:
#' @param  mu: the prior mean of the normal distr of the mean of each cluster (matrix)
#' @param    mu.sigma the covariance matrices of the normal distr of the mean of each cluster (3D array)
#' @param  sigma.V0 the V= matrix for the wishart prior of the covariance matrices (3D array)
#' @param sigma.n0 the n0 parameters of the wishart prior for the covariance matrices (vector)
#' @param  itS total number of iterations
#' @param biS burn in iterations
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration
#'@return List with the posterior samples of each random variable
GibbfPotts <- function(yS, betaS, muS, sigmaS, nS, bS, prS, itS, biS, salitS) {
    .Call(`_multiPotts_GibbfPotts`, yS, betaS, muS, sigmaS, nS, bS, prS, itS, biS, salitS)
}

#' 
#' @param yS a vector of data
#' @param nS is the neighbours object from BayesImageS
#' @param bS is the blocks object from BayesImageS
#' @param itS number of iterations to perform
#' @param biS number of burn in iterations
#' @param prS is a list of priors for the model, it includes:
#' @param    mu: the prior mean of the normal distr of the mean of each cluster (vector)
#' @param    mu.sd the prior sd of the normal distr of the mean of each cluster (vector)
#' @param    sigma the shape parameter of the gamma for the sd prior (vector)
#' @param    sigma.nu the rate parameters of the gamma for the sd prior (vector)
#' @param    beta constaining the borders of the interval where the beta is uniformly distributed (vector)
#' @param mhS is a list of options for the MH step when sampling beta,it includes:
#' @param    bandwith the standard deviation of the normal distr used for the rwmh when updating beta
#' @param    init optional value used to initalize the beta to start from
#' @param    adaptive optional,if omitted the default is adaptive, if adaptive = NULL then the bandwidth is fixed
#' @param    target optional, used to dedtermine how fast to change the bandwidth int the adaptive case (don't change if it is not strictly necessary)
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#'@return List with the posterior samples of each random variable
mcmcPotts1d <- function(yS, nS, bS, itS, biS, prS, mhS, salitS) {
    .Call(`_multiPotts_mcmcPotts1d`, yS, nS, bS, itS, biS, prS, mhS, salitS)
}

#' multidimensional Potts model gibbs sampler with beta sampled via Pseudolikelihood
#'
#' @param yS a matrix of data, samples on the cols, features on the rows
#' @param nS is the neighbours object from BayesImageS
#' @param  bS is the blocks object from BayesImageS
#' @param itS number of iterations to perform
#' @param biS number of burn in iterations
#' @param prS is a list of priors for the model, it includes:
#' @param    mu: the prior mean of the normal distr of the mean of each cluster (matrix)
#' @param   mu.sigma the covariance matrices of the normal distr of the mean of each cluster (3D array)
#' @param   sigma.V0 the V= matrix for the wishart prior of the covariance matrices (3D array)
#' @param    sigma.n0 the n0 parameters of the wishart prior for the covariance matrices (vector)
#' @param    beta constaining the borders of the interval where the beta is uniformly distributed (vector)
#' @param  mhS is a list of options for the MH step when sampling beta
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#' @details mhS it includes:
#'    bandwith the standard deviation of the normal distr used for the rwmh when updating beta
#'    init optional value used to initalize the beta to start from
#'    adaptive optional,if omitted the default is adaptive, if adaptive = NULL then the bandwidth is fixed
#'    target optional, used to dedtermine how fast to change the bandwidth int the adaptive case (don't change if it is not strictly necessary)
#' @return a List with the samples of theposterior of the random variables
mcmcPottsmd <- function(yS, nS, bS, itS, biS, prS, mhS, salitS) {
    .Call(`_multiPotts_mcmcPottsmd`, yS, nS, bS, itS, biS, prS, mhS, salitS)
}

#' wrapper function for the gibbs sampler for the potts model with beta approximatted by pseudolikelihood 
#' @description this identifies wheter we are in the 1d or md case and calls the appropriate function
#' @param yS a matrix of data, samples on the cols, features on the rows
#' @param nS is the neighbours object from BayesImageS
#' @param  bS is the blocks object from BayesImageS
#' @param itS number of iterations to perform
#' @param biS number of burn in iterations
#' @param prS is a list of priors for the model, it includes:
#' @param    mu: the prior mean of the normal distr of the mean of each cluster (matrix)
#' @param   mu.sigma the covariance matrices of the normal distr of the mean of each cluster (3D array)
#' @param   sigma.V0 the V= matrix for the wishart prior of the covariance matrices (3D array)
#' @param    sigma.n0 the n0 parameters of the wishart prior for the covariance matrices (vector)
#' @param    beta constaining the borders of the interval where the beta is uniformly distributed (vector)
#' @param  mhS is a list of options for the MH step when sampling beta
#' @param salitS number of allocactions to save in a salso compatible manner (matrix each row is a iteration)
#' @details mhS it includes:
#'    bandwith the standard deviation of the normal distr used for the rwmh when updating beta
#'    init optional value used to initalize the beta to start from
#'    adaptive optional,if omitted the default is adaptive, if adaptive = NULL then the bandwidth is fixed
#'    target optional, used to dedtermine how fast to change the bandwidth int the adaptive case (don't change if it is not strictly necessary)
#' @return a List with the samples of theposterior of the random variables
MCMCPotts <- function(yS, nS, bS, itS, biS, prS, mhS, salitS) {
    .Call(`_multiPotts_MCMCPotts`, yS, nS, bS, itS, biS, prS, mhS, salitS)
}

